spring:
  config:
    import: azure-keyvault:${AZURE_KEYVAULT_ENDPOINT}
  datasource:
    url: ${SQL_CONNECTION_STRING}
  data:
    redis:
      url: ${REDIS_CONNECTION_STRING}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}