apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata: { name: inventory-service-secrets, namespace: ecommerce }
spec:
  provider: azure
  secretObjects:
    - secretName: inventory-service-secrets
      type: Opaque
      data:
        - { objectName: sql-connection-string, key: sql-connection-string }
        - { objectName: redis-connection-string, key: redis-connection-string }
  parameters:
    usePodIdentity: "false"
    clientID: "${AZURE_CLIENT_ID}"
    keyvaultName: "${AZURE_KEYVAULT_NAME}"
    tenantId: "${AZURE_TENANT_ID}"
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret