apiVersion: v1
kind: Service
metadata: { name: inventory-service, namespace: ecommerce }
spec:
  selector: { app: inventory-service }
  ports: [{ name: http, port: 8082, targetPort: http }]
  type: ClusterIP